// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ViewsGetter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241105170428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ComputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamGB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YearOfProduction")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Created = new DateTime(2024, 11, 5, 18, 4, 28, 245, DateTimeKind.Local).AddTicks(1768),
                            Gpu = "RTX4070Super",
                            Name = "SuperPc",
                            Processor = "i5-12400",
                            Producer = "Asus",
                            RamGB = 16,
                            YearOfProduction = new DateTime(2024, 11, 5, 18, 4, 28, 245, DateTimeKind.Local).AddTicks(1726)
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Created = new DateTime(2024, 11, 5, 18, 4, 28, 245, DateTimeKind.Local).AddTicks(1773),
                            Gpu = "RTX4070Super",
                            Name = "SuperPc",
                            Processor = "i5-12400",
                            Producer = "Asus",
                            RamGB = 16,
                            YearOfProduction = new DateTime(2024, 11, 5, 18, 4, 28, 245, DateTimeKind.Local).AddTicks(1771)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
