// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ViewsGetter.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241112163249_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ComputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganzationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RamGB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YearOfProduction")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganzationId");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Created = new DateTime(2024, 11, 12, 17, 32, 48, 974, DateTimeKind.Local).AddTicks(4686),
                            Gpu = "RTX4070Super",
                            Name = "SuperPc",
                            OrganzationId = 101,
                            Processor = "i5-12400",
                            Producer = "Asus",
                            RamGB = 16,
                            YearOfProduction = new DateTime(2024, 11, 12, 17, 32, 48, 974, DateTimeKind.Local).AddTicks(4640)
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Created = new DateTime(2024, 11, 12, 17, 32, 48, 974, DateTimeKind.Local).AddTicks(4692),
                            Gpu = "RTX4070Super",
                            Name = "SuperPc",
                            OrganzationId = 102,
                            Processor = "i5-12400",
                            Producer = "Asus",
                            RamGB = 16,
                            YearOfProduction = new DateTime(2024, 11, 12, 17, 32, 48, 974, DateTimeKind.Local).AddTicks(4690)
                        });
                });

            modelBuilder.Entity("OrganzationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("REGON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            NIP = "2131212",
                            Name = "XKOM",
                            REGON = "2984395734"
                        },
                        new
                        {
                            Id = 102,
                            NIP = "4353443",
                            Name = "MORELE",
                            REGON = "11123395734"
                        });
                });

            modelBuilder.Entity("ComputerEntity", b =>
                {
                    b.HasOne("OrganzationEntity", "Organzation")
                        .WithMany("Computer")
                        .HasForeignKey("OrganzationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organzation");
                });

            modelBuilder.Entity("OrganzationEntity", b =>
                {
                    b.OwnsOne("Address", "Address", b1 =>
                        {
                            b1.Property<int>("OrganzationEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OrganzationEntityId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganzationEntityId");

                            b1.HasData(
                                new
                                {
                                    OrganzationEntityId = 101,
                                    City = "Krakow",
                                    Street = "Kurczakow"
                                },
                                new
                                {
                                    OrganzationEntityId = 102,
                                    City = "Krakow",
                                    Street = "Centralna"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("OrganzationEntity", b =>
                {
                    b.Navigation("Computer");
                });
#pragma warning restore 612, 618
        }
    }
}
