// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesDP.Models.Movies;

#nullable disable

namespace MoviesDP.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MoviesDP.Models.Movies.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("INT")
                        .HasColumnName("country_id");

                    b.Property<string>("CountryIsoCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("country_iso_code")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("CountryName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("country_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("CountryId");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("INT")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("department_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("DepartmentId");

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("INT")
                        .HasColumnName("gender_id");

                    b.Property<string>("Gender1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("GenderId");

                    b.ToTable("gender", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("INT")
                        .HasColumnName("genre_id");

                    b.Property<string>("GenreName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("genre_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("GenreId");

                    b.ToTable("genre", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Keyword", b =>
                {
                    b.Property<int>("KeywordId")
                        .HasColumnType("INT")
                        .HasColumnName("keyword_id");

                    b.Property<string>("KeywordName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("keyword_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("KeywordId");

                    b.ToTable("keyword", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("INT")
                        .HasColumnName("language_id");

                    b.Property<string>("LanguageCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("language_code")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("LanguageName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("language_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("LanguageId");

                    b.ToTable("language", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.LanguageRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INT")
                        .HasColumnName("role_id");

                    b.Property<string>("LanguageRole1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("language_role")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("RoleId");

                    b.ToTable("language_role", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("INT")
                        .HasColumnName("movie_id");

                    b.Property<int?>("Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("budget")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Homepage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("homepage")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("MovieStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("movie_status")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Overview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("overview")
                        .HasDefaultValueSql("NULL");

                    b.Property<double?>("Popularity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasColumnName("popularity")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateOnly?>("ReleaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATE")
                        .HasColumnName("release_date")
                        .HasDefaultValueSql("NULL");

                    b.Property<long?>("Revenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("revenue")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("Runtime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("runtime")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Tagline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("tagline")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("title")
                        .HasDefaultValueSql("NULL");

                    b.Property<double?>("VoteAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasColumnName("vote_average")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("VoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("vote_count")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("MovieId");

                    b.ToTable("movie", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCast", b =>
                {
                    b.Property<int?>("CastOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("cast_order")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("CharacterName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("character_name")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("gender_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("person_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("GenderId");

                    b.HasIndex("MovieId");

                    b.HasIndex("PersonId");

                    b.ToTable("movie_cast", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCompany", b =>
                {
                    b.Property<int?>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("company_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MovieId");

                    b.ToTable("movie_company", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCrew", b =>
                {
                    b.Property<int?>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("department_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Job")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("job")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("person_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MovieId");

                    b.HasIndex("PersonId");

                    b.ToTable("movie_crew", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieGenre", b =>
                {
                    b.Property<int?>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("genre_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("movie_genres", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieKeyword", b =>
                {
                    b.Property<int?>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("keyword_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("KeywordId");

                    b.HasIndex("MovieId");

                    b.ToTable("movie_keywords", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieLanguage", b =>
                {
                    b.Property<int?>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("language_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("LanguageRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("language_role_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageRoleId");

                    b.HasIndex("MovieId");

                    b.ToTable("movie_languages", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INT")
                        .HasColumnName("person_id");

                    b.Property<string>("PersonName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("person_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("PersonId");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.ProductionCompany", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("INT")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("company_name")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("CompanyId");

                    b.ToTable("production_company", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.ProductionCountry", b =>
                {
                    b.Property<int?>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("country_id")
                        .HasDefaultValueSql("NULL");

                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("movie_id")
                        .HasDefaultValueSql("NULL");

                    b.HasIndex("CountryId");

                    b.HasIndex("MovieId");

                    b.ToTable("production_country", (string)null);
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCast", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.HasOne("MoviesDP.Models.Movies.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Gender");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCompany", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.ProductionCompany", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Company");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieCrew", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.HasOne("MoviesDP.Models.Movies.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Department");

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieGenre", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieKeyword", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Keyword");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.MovieLanguage", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("MoviesDP.Models.Movies.LanguageRole", "LanguageRole")
                        .WithMany()
                        .HasForeignKey("LanguageRoleId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Language");

                    b.Navigation("LanguageRole");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesDP.Models.Movies.ProductionCountry", b =>
                {
                    b.HasOne("MoviesDP.Models.Movies.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("MoviesDP.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Country");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
